### ISSUE TITLE
Link between MOF names and DOI

### ISSUE THREAD

**Issue by CorySimon** [gregchung/CoRE-MOFs#1]
Can you please post a .csv file:

    MOF_NAME,DOI

with the name of the MOF in the CoRE MOF database and a DOI that corresponds to where this MOF was experimentally reported? I think this will be useful for any studies that use the CoRE MOF database where they want to actually synthesize the material.

**Comment by gregchung** [comment]
This is a great suggestion. We are preparing CoRE MOF 2.0 (which will include new updates and other structures that we mined from the web) and this information will be available with the new version of the database.
